---

- name: create cni plugins directory
  file:
    path: /opt/cni/bin
    state: directory

- name: copy cni plugins
  copy:
    src: cache/cni-plugins.tgz
    dest: /tmp/cni-plugins.tgz

- name: extract cni plugins
  command: tar -C /opt/cni/bin -xzf /tmp/cni-plugins.tgz

# - name: copy sysctl bridge config
#   copy:
#     src: 10-net-bridge.conf
#     dest: /etc/sysctl.d/10-net-bridge.conf
#
# - name: load sysctl config
#   command: sysctl -p

- name: install consul
  copy:
    src: cache/consul
    dest: /usr/local/bin/
    mode: 0755

- import_tasks: docker.yml
- import_tasks: openjdk.yml

- import_role:
    name: nomad_service

- name: copy nomad config
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/server.hcl

- name: start nomad
  service:
    name: nomad
    state: restarted
    enabled: yes
