---
- import_role:
    name: nomad_service

- import_tasks: docker.yml
- import_tasks: openjdk.yml

- name: copy nomad config
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/server.hcl

- name: start nomad
  service:
    name: nomad
    state: restarted
    enabled: yes