# -*- mode: ruby -*-
# vi: set ft=ruby :

$consul_version = "1.2.1"
$nomad_version = "0.8.4"
$vault_version = "0.10.4"
$traefik_version = "1.6.5"

$consul_url = "https://releases.hashicorp.com/consul/#{$consul_version}/consul_#{$consul_version}_linux_amd64.zip"
$nomad_url = "https://releases.hashicorp.com/nomad/#{$nomad_version}/nomad_#{$nomad_version}_linux_amd64.zip"
$vault_url = "https://releases.hashicorp.com/nomad/#{$vault_version}/vault_#{$vault_version}_linux_amd64.zip"
$traefik_url = "https://github.com/containous/traefik/releases/download/v#{$traefik_version}/traefik_linux-amd64"

$script = <<-SCRIPT

if [ ! -f /vagrant/consul ]
then
  curl -s #{$consul_url} -o /tmp/consul.zip
  gunzip -S .zip /tmp/consul
  chmod 755 /tmp/consul
  mv /tmp/consul /vagrant/consul
fi

if [ ! -f /vagrant/nomad ]
then
  curl -s #{$nomad_url} -o /tmp/nomad.zip
  gunzip -S .zip /tmp/nomad
  chmod 755 /tmp/nomad
  mv /tmp/nomad /vagrant/nomad
fi

if [ ! -f /vagrant/vault ]
then
  curl -s #{$vault_url} -o /tmp/vault.zip
  gunzip -S .zip /tmp/vault
  chmod 755 /tmp/vault
  mv /tmp/vault /vagrant/vault
fi

if [ ! -f /vagrant/traefik ]
then
  curl -s -L #{$traefik_url} -o /vagrant/traefik
  chmod 755 /vagrant/traefik
fi

SCRIPT

NSERVERS = 3
NWORKERS = 3

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  (1..NWORKERS).each do |id|
    config.vm.define "worker#{id}" do |machine|
      machine.vm.hostname = "worker#{id}"
      machine.vm.network "private_network", ip: "172.10.10.#{20 + id}"
    end
  end

  (1..NSERVERS).each do |id|
    config.vm.define "server#{id}" do |machine|
      machine.vm.hostname = "server#{id}"
      machine.vm.network "private_network", ip: "172.10.10.#{10 + id}"
    end
  end

  config.vm.define "vault1" do |machine|
    machine.vm.hostname = "vault1"
    machine.vm.network "private_network", ip: "172.10.10.31"
  end

  config.vm.define "proxy" do |machine|
    machine.vm.hostname = "proxy"
    machine.vm.network "private_network", ip: "172.10.10.100"

    machine.vm.provision "shell", inline: $script

    # Only execute once the Ansible provisioner,
    # when all the machines are up and ready.
    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook = "provisioning/playbook.yml"
      ansible.install = true
      ansible.become = true
      ansible.limit = "all"
      ansible.inventory_path = "inventory"
    end
  end
end
