---
- name: install consul
  copy:
    src: /usr/local/bin/consul
    dest: /usr/local/bin/

- name: instal nomad
  copy:
    src: /usr/local/bin/nomad
    dest: /usr/local/bin

- name: create services
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
  with_items:
    - 'consul.service'
    - 'nomad.service'

- name: create application directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/consul.d
    - /opt/consul
    - /etc/nomad.d
    - /opt/nomad