---
- name: install consul
  copy:
    src: /vagrant/consul
    dest: /usr/local/bin/
    mode: 0755

- name: instal nomad
  copy:
    src: /vagrant/nomad
    dest: /usr/local/bin
    mode: 0755

- name: create services
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
  with_items:
    - 'consul.service'
    - 'nomad.service'

- name: create application directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/consul.d
    - /opt/consul
    - /etc/nomad.d
    - /opt/nomad