---
- import_role:
    name: consul_service

- name: copy consul config
  template:
    src: consul.json.j2
    dest: /etc/consul.d/server.json

- name: start consul
  service:
    name: consul
    state: restarted
    enabled: yes