---
# - hosts: all
#   tasks:
#     - name: remove network manager
#       yum:
#         name: NetworkManager
#         state: absent
#     - name: restart network
#       service:
#         name: network
#         state: restarted
- hosts: servers
  roles:
    - consul_server
- hosts: vault
  roles:
    - consul_client
    - vault_server
- hosts: servers
  roles:
    - nomad_server
- hosts: workers
  roles:
    - consul_client
    - nomad_client
- hosts: proxy
  roles:
    - consul_client
    - traefik_server
