---
- hosts: localhost
  connection: local
  tasks:
    - name: create containers
      lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          # server: https://images.linuxcontainers.org
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          alias: bionic
        config:
          security.nesting: "true"
          security.privileged: "true"
        wait_for_ipv4_addresses: true
        url: unix:/var/snap/lxd/common/lxd/unix.socket
      loop: &nodes
        - proxy
        - server1
        - server2
        - server3
        - worker1
        - worker2
        - worker3
        # - vault1
    - name: install python
      command: "lxc exec {{ item }} -- sh -c 'if [ ! -f /usr/bin/python ]; then ln -s /usr/bin/python3 /usr/bin/python; fi'"
      loop: *nodes

    - name: create cache directory
      file:
        path: cache
        state: directory
    - name: fetch applications
      unarchive:
        src: "{{ item.url }}"
        dest: cache
        creates: "cache/{{ item.file }}"
        remote_src: yes
      loop:
        - url: https://releases.hashicorp.com/consul/1.3.1/consul_1.3.1_linux_amd64.zip
          file: consul
        - url: https://releases.hashicorp.com/nomad/0.8.6/nomad_0.8.6_linux_amd64.zip
          file: nomad
        - url: https://releases.hashicorp.com/vault/0.11.4/vault_0.11.4_linux_amd64.zip
          file: vault
    - name: fecth traefik
      get_url:
        url: https://github.com/containous/traefik/releases/download/v1.7.4/traefik_linux-amd64
        dest: cache/traefik
        mode: 0755

- hosts: servers
  roles:
    - consul_server
# - hosts: vault
#   roles:
#     - consul_client
#     - vault_server
- hosts: servers
  roles:
    - nomad_server
- hosts: workers
  roles:
    - consul_client
    - nomad_client
- hosts: proxy
  roles:
    - consul_client
    - traefik_server
