---
- hosts: localhost
  connection: local
  vars:
    consul_version: "1.3.1"
    nomad_version: "0.8.6"
    vault_version: "0.11.4"
    traefik_version: "1.7.4"
    server_binaries:
      - url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        file: consul
      - url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        file: nomad
      - url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
        file: vault
    traefik_url: "https://github.com/containous/traefik/releases/download/v{{ traefik_version }}/traefik_linux-amd64"
  tasks:
    - name: create containers
      lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: ubuntu/bionic/amd64
        config:
          security.nesting: "{{ 'true' if item in ['nomad-client1', 'nomad-client2', 'nomad-client3'] else 'false' }}"
          security.privileged: "{{ 'true' if item in ['vault1'] else 'false' }}"
        devices:
          eth0:
            type: nic
            nictype: bridged
            parent: lxdbr0
            ipv4.address: "{{ hostvars[item].ip_address }}"
        url: unix:/var/snap/lxd/common/lxd/unix.socket
      loop: "{{ groups['all'] }}"

    - name: create cache directory
      file:
        path: cache
        state: directory

    - name: fetch applications
      unarchive:
        src: "{{ item.url }}"
        dest: cache
        creates: "cache/{{ item.file }}"
        remote_src: yes
      loop: "{{ server_binaries }}"

    - name: fecth traefik
      get_url:
        url: "{{ traefik_url }}"
        dest: cache/traefik
        mode: 0755


- hosts: consul_servers
  roles:
    - consul_server

- hosts: vault_servers
  roles:
    - consul_client
    - vault_server

- hosts: nomad_servers
  roles:
    - consul_client
    - nomad_server

- hosts: nomad_clients
  roles:
    - consul_client
    - nomad_client

- hosts: proxy
  roles:
    - consul_client
    - traefik_server
