# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-28"
  # config.vm.provision "shell", inline: $common

  (1..3).each do |id|
    config.vm.define "server#{id}" do |machine|
      machine.vm.network "private_network", ip: "172.10.10.#{100 + id}"
      machine.vm.provider "virtualbox" do |vb|
        file_to_disk = ".vagrant/disk#{id}.vdi"
        unless File.exist?(file_to_disk)
          vb.customize ['createhd', '--filename', file_to_disk, '--size', 10 * 1024] # 10 GB
        end
        # vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata', '--portcount', 4]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
      end
    end
  end

  config.vm.define "controller" do |machine|
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end

    machine.vm.network "private_network", ip: "172.10.10.99"

    machine.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.become = true
      ansible.limit = "all"
      ansible.inventory_path = "inventory"
      ansible.raw_arguments = [
        "--extra-vars",
        "ansible_python_interpreter=/usr/bin/python3"
      ]
    end
  end
end
